config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session

  root "home#show"

  namespace :admin do
    resources :questions
  end

  resources :questions
  resources :answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  paginates_per 1

  has_many :question_options, dependent: :destroy
  has_many :answers, class_name: 'UserAnswer'
  serialize :result, Array

  accepts_nested_attributes_for :question_options

  enum status: %i(using unusing)

  def status_i18n
    statuses = { using: '使用中', unusing: '未使用' }
    statuses.fetch(status.to_sym, "未知")
  end
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question

  scope :by_ids, ->(ids) { where(id: ids) }
  scope :by_user, ->(user_id) { where(user_id: user_id) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :answers, class_name: 'UserAnswer'
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :question

  serialize :result, Array

  scope :by_question, ->(question_id) { where(question_id: question_id) }
  scope :by_options, ->(ids) { where(result: ids) }
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :set_question, only: [:edit, :update]
  def index
    @questions = Question.all.order('id desc')
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(set_question_params)
    if @question.save
      redirect_to edit_admin_question_path(@question)
    else
      render :new
    end
  end

  def edit

  end

  def update
    puts "set_question_params是#{set_question_params}" * 30
    if @question.update(set_question_params)
      redirect_to admin_questions_path
    else
      redirect_to edit_admin_question_path(@question)
    end
  end

  private
  def set_question_params
    params.require(:question).permit(
      :content,
      result: [],
      question_options_attributes: [
        :content
      ]
    )
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = UserAnswer.new
    @questions = Question.using.page(params[:page])
  end

  def index
    @questions = Question.using.page(params[:page]).per(15)
  end

  def create
    @answer = current_user.answers.by_question(set_answer_params[:question_id]).last
    if @answer.present?
      @answer.update(set_answer_params)
      if params[:commit] == "下一题"
        redirect_to new_answer_path(page: params[:next_page])
      else
        redirect_to answers_path
      end
    else
      @answer = UserAnswer.new(set_answer_params)
      if @answer.save
        if params[:commit] == "下一题"
          redirect_to new_answer_path(page: params[:next_page])
        else
          redirect_to answers_path
        end
      else
        redirect_to new_answer_path(page: params[:current_page])
      end
    end
  end

  private
  def set_answer_params
    params[:user_answer][:user_id] = current_user.id
    params.require(:user_answer).permit(
      :question_id,
      :user_id,
      result: []
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :login_required?

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(name: session[:username])
  end

  private
  def login_required?
    redirect_to new_session_path if current_user.blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    # session[:username] = nil
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    answer?
    @questions = Question.using
  end

  private
  def answer?

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'thiny'
  skip_before_action :login_required?
  DEFAUTL_USERNAME = 'admin'.freeze
  DEFAULT_PASSWORD = '123456'.freeze

  def new
  end

  def create
    if params[:username] == DEFAUTL_USERNAME && params[:password] == DEFAULT_PASSWORD
      init_user
      session[:username] = DEFAUTL_USERNAME
      redirect_to root_url, notice: '登录成功'
    else
      redirect_to new_session_path, notice: '账号或密码错误'
    end
  end

  private
  def init_user
    user = User.find_by(name: DEFAUTL_USERNAME)
    User.create!(name: DEFAUTL_USERNAME, password: DEFAULT_PASSWORD)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/questions/edit.html.erb
<div class="app_contain">
  <div class="container">
    <%= form_for @question, url: admin_question_path, method: 'put' do |f| %>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">题目内容</label>
        <div class="col-sm-10">
          <%= f.text_area :content, rows: 8, cols: 80, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">选择正确答案</label>
        <div class="col-sm-10">
          <% @question.question_options.each.with_index(1) do |option, i| %>
            <div class="[ form-group ]">
                  <input type="checkbox" name="question[result][]" id="question-option-<%= option.id%>" <%= 'checked' if @question.result.include?(option.id.to_s) %> value="<%= option.id %>" autocomplete="off" />
                <div class="[ btn-group ]">
                    <label for="question-option-<%= option.id%>" class="[ btn btn-success ]">
                        <span class="[ glyphicon glyphicon-ok ]"></span>
                        <span> </span>
                    </label>
                    <label for="question-option-<%= option.id%>" class="[ btn btn-default active ]">
                        <%= option.content %>
                    </label>
                </div>
                </br>
            </div>
          <% end %>
        </div>
      </div>

      <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
          <%= f.submit "确定", class: 'btn btn-primary' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/admin/questions/index.html.erb
<%= link_to '新建', new_admin_question_path, class: 'green-btn' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>内容</th>
      <th>状态</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each.with_index(1) do |question, index| %>
      <tr>
        <th scope="row"> <%= index %></th>
        <td> <%= question.content %></td>
        <td> <%= question.status_i18n %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/questions/new.html.erb
<div class="app_contain">
  <div class="container">
    <%= form_for @question, url: admin_questions_path do |f| %>
      <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">题目内容</label>
        <div class="col-sm-10">
          <%= f.text_area :content, rows: 8, cols: 80, class: 'form-control' %>
        </div>
      </div>

      <%= f.fields_for :question_options, @question.question_options.build do |ff| %>
        <div class="form-group row">
          <label for="lgFormGroupInput" class="col-sm-2 col-form-label col-form-label-lg">选项</label>
          <div class="col-sm-3 js-option-gruop">
            <%= ff.text_field :content, class: 'form-control form-control-lg', placeholder: "请输入选项卡" %>
          </div>
          <div class="">
            <span> <%= link_to "添加选项", '#', class: 'js-to-add-option' %> </span>
          </div>
        </div>
      <% end %>

      <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
          <button type="submit" class="btn btn-primary">确定</button>
        </div>
      </div>

    <% end %>
  </div>
</div>


<script type="text/javascript">
  var optionTem = JST['admin/questions/new'];
  var addOptionTimes = 0
  $(document).on("click", 'a.js-to-add-option', function(e){
    e.preventDefault();
    addOptionTimes++
    $("div.js-option-gruop").append(optionTem());
    var latest = $("div.js-option-gruop").find("input").last()
    latest.attr('name', "question[question_options_attributes]["+ addOptionTimes +"][content]")
  })

</script>

app/views/answers/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>题目内容</th>
      <th>正确答案</th>
      <th>考生答案</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each.with_index(1) do |q, i| %>
      <tr>
        <th scope="row"> <%= i %></th>
        <td> <%= q.content %></td>
        <td>
          <% q.question_options.by_ids(q.result).each.with_index(1) do |o, i| %>
            <span><%= i %>:<%= o.content%></span></br>
          <% end %>
        </td>
        <td>
          <% answer = current_user.answers.by_question(q.id).last %>
          <% q.question_options.by_ids(answer.result).each.with_index(1) do |o, i| %>
            <span><%= i %>:<%= o.content%></span></br>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/answers/new.html.erb
<h2>答题中,共<%= Question.using.count(:id)%>题</h2>
<div class="app_contain">
  <div class="container">
    <%= form_for @answer, url: answers_path do |f| %>
      <input type="hidden" name="next_page" value="<%= @questions.next_page %>">
      <input type="hidden" name="current_page" value="<%= params[:page] || 1 %>">
      <% @questions.each do |question| %>
      <%= f.hidden_field :question_id, value: question.id %>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">题目内容</label>
          <div class="col-sm-10">
            <%= question.content %>
          </div>
        </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">选择正确答案</label>
        <div class="col-sm-10">
          <% question.question_options.each.with_index(1) do |option, i| %>
            <div class="[ form-group ]">
                <input type="checkbox" name="user_answer[result][]" id="question-option-<%= option.id%>"  value="<%= option.id %>" autocomplete="off" />
                <div class="[ btn-group ]">
                    <label for="question-option-<%= option.id%>" class="[ btn btn-success ]">
                        <span class="[ glyphicon glyphicon-ok ]"></span>
                        <span> </span>
                    </label>
                    <label for="question-option-<%= option.id%>" class="[ btn btn-default active ]">
                        <%= option.content %>
                    </label>
                </div>
                </br>
            </div>
          <% end %>
        </div>
      </div>

      <% end %>

      <div class="form-group row" style="margin-left: 200px;margin-top: 60px;">
        <div class="offset-sm-2 col-sm-10">
          <% submit_value = @questions.last_page? ? "提交答卷" : "下一题" %>
          <%= f.submit submit_value, class: 'btn btn-info' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/show.html.erb
<h2>nihao</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnswerSys</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/thiny.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>As</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'thiny', media: 'all' %>
    <%= javascript_include_tag 'thiny' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h2>答题中,共<%= @questions.count(:id)%>题</h2>
<div class="app_contain">
  <div class="container">
      <% @questions.page(params[:page]).each do |question| %>
        <div class="form-group row">
          <label for="inputEmail3" class="col-sm-2 col-form-label">题目内容</label>
          <div class="col-sm-10">
            <%= question.content %>
          </div>
        </div>

      <div class="form-group row">
        <label class="col-sm-2 col-form-label">选择正确答案</label>
        <div class="col-sm-10">
          <% question.question_options.each.with_index(1) do |option, i| %>
            <div class="[ form-group ]">
                  <input type="checkbox" name="question[result][]" id="question-option-<%= option.id%>"  value="<%= option.id %>" autocomplete="off" />
                <div class="[ btn-group ]">
                    <label for="question-option-<%= option.id%>" class="[ btn btn-success ]">
                        <span class="[ glyphicon glyphicon-ok ]"></span>
                        <span> </span>
                    </label>
                    <label for="question-option-<%= option.id%>" class="[ btn btn-default active ]">
                        <%= option.content %>
                    </label>
                </div>
                </br>
            </div>
          <% end %>
        </div>
      </div>

      <% end %>

      <div class="form-group row" style="margin-left: 200px;margin-top: 60px;">
        <div class="offset-sm-2 col-sm-10">
          <%= link_to_previous_page @questions.page(params[:page]), '上一题' %>
          <span style="margin-left: 20px;"></span>
          <%= link_to_next_page @questions.page(params[:page]), '下一题' %>
        </div>
      </div>

  </div>
</div>